theme: jekyll-theme-tactile
title: Dumb Struct
show_downloads: true
latest_composable_architecture_teacode:
  zip_url: http://www.dumbstruct.com/assets/teacodebundles/ComposableArchitecture.tcbundle.zip